// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_types.sql

package db

import (
	"context"
	"database/sql"
)

const createAccountType = `-- name: CreateAccountType :one
INSERT INTO account_types (
    name,
    user_id,
    is_system
) VALUES (?, ?, ?) RETURNING id, name, user_id, is_system, deleted_at
`

type CreateAccountTypeParams struct {
	Name     string        `json:"name"`
	UserID   sql.NullInt64 `json:"user_id"`
	IsSystem int64         `json:"is_system"`
}

func (q *Queries) CreateAccountType(ctx context.Context, arg CreateAccountTypeParams) (AccountType, error) {
	row := q.db.QueryRowContext(ctx, createAccountType, arg.Name, arg.UserID, arg.IsSystem)
	var i AccountType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.IsSystem,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountTypeByUser = `-- name: GetAccountTypeByUser :one
SELECT id, name, user_id, is_system, deleted_at FROM account_types
WHERE id = ? AND (user_id IS NULL OR user_id = ?) AND deleted_at IS NULL
`

type GetAccountTypeByUserParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetAccountTypeByUser(ctx context.Context, arg GetAccountTypeByUserParams) (AccountType, error) {
	row := q.db.QueryRowContext(ctx, getAccountTypeByUser, arg.ID, arg.UserID)
	var i AccountType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.IsSystem,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountTypesByUser = `-- name: ListAccountTypesByUser :many
SELECT id, name, user_id, is_system, deleted_at FROM account_types
WHERE (user_id IS NULL OR user_id = ?) AND deleted_at IS NULL
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListAccountTypesByUser(ctx context.Context, userID sql.NullInt64) ([]AccountType, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTypesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountType
	for rows.Next() {
		var i AccountType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsSystem,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAccountTypes = `-- name: ListSystemAccountTypes :many
SELECT id, name, user_id, is_system, deleted_at FROM  account_types
WHERE user_id IS NULL AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSystemAccountTypes(ctx context.Context) ([]AccountType, error) {
	rows, err := q.db.QueryContext(ctx, listSystemAccountTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountType
	for rows.Next() {
		var i AccountType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.IsSystem,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccountTypeByUser = `-- name: SoftDeleteAccountTypeByUser :exec
UPDATE account_types SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND is_system = 0
`

type SoftDeleteAccountTypeByUserParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) SoftDeleteAccountTypeByUser(ctx context.Context, arg SoftDeleteAccountTypeByUserParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAccountTypeByUser, arg.ID, arg.UserID)
	return err
}
