// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    type,
    user_id
) VALUES (?, ?, ?) RETURNING id, name, type, user_id, deleted_at
`

type CreateAccountParams struct {
	Name   string        `json:"name"`
	Type   string        `json:"type"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Type, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, type, user_id, deleted_at FROM accounts
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetAccountByIDParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, name, type, user_id, deleted_at FROM accounts
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID sql.NullInt64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.UserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
