// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"
	"database/sql"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
    name,
    type,
    credit_limit,
    cutoff_date,
    user_id
) VALUES (?,?,?,?,?)
RETURNING id, name, type, credit_limit, cutoff_date, user_id, deleted_at
`

type CreateCardParams struct {
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	CreditLimit sql.NullInt64 `json:"credit_limit"`
	CutoffDate  string        `json:"cutoff_date"`
	UserID      sql.NullInt64 `json:"user_id"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.Name,
		arg.Type,
		arg.CreditLimit,
		arg.CutoffDate,
		arg.UserID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreditLimit,
		&i.CutoffDate,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, name, type, credit_limit, cutoff_date, user_id, deleted_at FROM cards
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetCardByIDParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetCardByID(ctx context.Context, arg GetCardByIDParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByID, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreditLimit,
		&i.CutoffDate,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const listCardsByUser = `-- name: ListCardsByUser :many
SELECT id, name, type, credit_limit, cutoff_date, user_id, deleted_at FROM cards
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCardsByUser(ctx context.Context, userID sql.NullInt64) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreditLimit,
			&i.CutoffDate,
			&i.UserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCard = `-- name: SoftDeleteCard :exec
UPDATE cards SET deleted_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type SoftDeleteCardParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) SoftDeleteCard(ctx context.Context, arg SoftDeleteCardParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCard, arg.ID, arg.UserID)
	return err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET name = ?,
    type = ?,
    credit_limit = ?,
    cutoff_date = ?
WHERE id = ? AND user_id = ? AND deleted_at is NULL
RETURNING id, name, type, credit_limit, cutoff_date, user_id, deleted_at
`

type UpdateCardParams struct {
	Name        string        `json:"name"`
	Type        string        `json:"type"`
	CreditLimit sql.NullInt64 `json:"credit_limit"`
	CutoffDate  string        `json:"cutoff_date"`
	ID          int64         `json:"id"`
	UserID      sql.NullInt64 `json:"user_id"`
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.Name,
		arg.Type,
		arg.CreditLimit,
		arg.CutoffDate,
		arg.ID,
		arg.UserID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreditLimit,
		&i.CutoffDate,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}
