// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AdditionalIncome struct {
	ID          int64          `json:"id"`
	Description string         `json:"description"`
	Date        string         `json:"date"`
	Amount      int64          `json:"amount"`
	UserID      sql.NullInt64  `json:"user_id"`
	Comment     sql.NullString `json:"comment"`
}

type AdvancePayment struct {
	ID         int64          `json:"id"`
	PurchaseID sql.NullInt64  `json:"purchase_id"`
	Date       string         `json:"date"`
	Amount     int64          `json:"amount"`
	Comment    sql.NullString `json:"comment"`
}

type Card struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Type        string         `json:"type"`
	CreditLimit sql.NullInt64  `json:"credit_limit"`
	CutoffDate  string         `json:"cutoff_date"`
	UserID      sql.NullInt64  `json:"user_id"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type ChangeHistory struct {
	ID         int64          `json:"id"`
	TableName  string         `json:"table_name"`
	RegisterID int64          `json:"register_id"`
	Field      string         `json:"field"`
	Action     string         `json:"action"`
	PastValue  sql.NullInt64  `json:"past_value"`
	NewValue   sql.NullInt64  `json:"new_value"`
	ChangeDate sql.NullString `json:"change_date"`
	UserID     sql.NullInt64  `json:"user_id"`
	Motive     sql.NullString `json:"motive"`
}

type MonthlyExpense struct {
	ID            int64          `json:"id"`
	Expense       string         `json:"expense"`
	Amount        int64          `json:"amount"`
	AmountPaid    int64          `json:"amount_paid"`
	Remaining     sql.NullInt64  `json:"remaining"`
	Paid          sql.NullInt64  `json:"paid"`
	Comment       sql.NullString `json:"comment"`
	PurchaseMsi   sql.NullInt64  `json:"purchase_msi"`
	CreditCard    sql.NullString `json:"credit_card"`
	PaymentNumber sql.NullInt64  `json:"payment_number"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	UserID        sql.NullInt64  `json:"user_id"`
	DeletedAt     sql.NullString `json:"deleted_at"`
}

type MonthlyFinance struct {
	ID             int64  `json:"id"`
	Month          string `json:"month"`
	BankMoney      int64  `json:"bank_money"`
	Cash           int64  `json:"cash"`
	ExpectedIncome int64  `json:"expected_income"`
}

type MonthlyPayment struct {
	ID         int64         `json:"id"`
	PurchaseID sql.NullInt64 `json:"purchase_id"`
	Month      int64         `json:"month"`
	Amount     int64         `json:"amount"`
	Paid       sql.NullInt64 `json:"paid"`
}

type Project struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	StartDate   sql.NullString `json:"start_date"`
	EndDate     sql.NullString `json:"end_date"`
	Budget      sql.NullInt64  `json:"budget"`
	UserID      sql.NullInt64  `json:"user_id"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type Purchase struct {
	ID                 int64          `json:"id"`
	Purchase           string         `json:"purchase"`
	Date               string         `json:"date"`
	PaymentMethod      string         `json:"payment_method"`
	Amount             int64          `json:"amount"`
	AmountPaid         int64          `json:"amount_paid"`
	Remaining          sql.NullInt64  `json:"remaining"`
	Paid               sql.NullInt64  `json:"paid"`
	CarryOverNextMonth sql.NullInt64  `json:"carry_over_next_month"`
	Comment            sql.NullString `json:"comment"`
	CardID             sql.NullInt64  `json:"card_id"`
	ProjectID          sql.NullInt64  `json:"project_id"`
	UserID             sql.NullInt64  `json:"user_id"`
	DeletedAt          sql.NullString `json:"deleted_at"`
}

type User struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Email            sql.NullString `json:"email"`
	TelegramID       sql.NullString `json:"telegram_id"`
	PasskeyID        sql.NullString `json:"passkey_id"`
	RegistrationDate sql.NullString `json:"registration_date"`
	DeletedAt        sql.NullString `json:"deleted_at"`
}
