// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package db

import (
	"context"
	"database/sql"
)

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (
    purchase,
    date,
    amount,
    carry_over_next_month,
    comment,
    card_id,
    account_id,
    project_id,
    user_id
) VALUES (?,?,?,?,?,?,?,?,?) RETURNING id, purchase, date, amount, amount_paid, remaining, paid, carry_over_next_month, comment, card_id, account_id, project_id, user_id, deleted_at
`

type CreatePurchaseParams struct {
	Purchase           string         `json:"purchase"`
	Date               string         `json:"date"`
	Amount             int64          `json:"amount"`
	CarryOverNextMonth sql.NullInt64  `json:"carry_over_next_month"`
	Comment            sql.NullString `json:"comment"`
	CardID             sql.NullInt64  `json:"card_id"`
	AccountID          sql.NullInt64  `json:"account_id"`
	ProjectID          sql.NullInt64  `json:"project_id"`
	UserID             sql.NullInt64  `json:"user_id"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, createPurchase,
		arg.Purchase,
		arg.Date,
		arg.Amount,
		arg.CarryOverNextMonth,
		arg.Comment,
		arg.CardID,
		arg.AccountID,
		arg.ProjectID,
		arg.UserID,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Purchase,
		&i.Date,
		&i.Amount,
		&i.AmountPaid,
		&i.Remaining,
		&i.Paid,
		&i.CarryOverNextMonth,
		&i.Comment,
		&i.CardID,
		&i.AccountID,
		&i.ProjectID,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const getPurchaseById = `-- name: GetPurchaseById :one
SELECT id, purchase, date, amount, amount_paid, remaining, paid, carry_over_next_month, comment, card_id, account_id, project_id, user_id, deleted_at FROM purchases WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type GetPurchaseByIdParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetPurchaseById(ctx context.Context, arg GetPurchaseByIdParams) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseById, arg.ID, arg.UserID)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Purchase,
		&i.Date,
		&i.Amount,
		&i.AmountPaid,
		&i.Remaining,
		&i.Paid,
		&i.CarryOverNextMonth,
		&i.Comment,
		&i.CardID,
		&i.AccountID,
		&i.ProjectID,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const listPurchasesByUserId = `-- name: ListPurchasesByUserId :many
SELECT id, purchase, date, amount, amount_paid, remaining, paid, carry_over_next_month, comment, card_id, account_id, project_id, user_id, deleted_at FROM purchases WHERE user_id = ? AND deleted_at IS NULL ORDER BY date DESC
`

func (q *Queries) ListPurchasesByUserId(ctx context.Context, userID sql.NullInt64) ([]Purchase, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purchase
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.Purchase,
			&i.Date,
			&i.Amount,
			&i.AmountPaid,
			&i.Remaining,
			&i.Paid,
			&i.CarryOverNextMonth,
			&i.Comment,
			&i.CardID,
			&i.AccountID,
			&i.ProjectID,
			&i.UserID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePurchase = `-- name: SoftDeletePurchase :exec
UPDATE purchases SET deleted_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?
`

type SoftDeletePurchaseParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) SoftDeletePurchase(ctx context.Context, arg SoftDeletePurchaseParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePurchase, arg.ID, arg.UserID)
	return err
}

const updatePurchase = `-- name: UpdatePurchase :one
UPDATE purchases SET
purchase = ?, date = ?, amount = ?, amount_paid = ?, carry_over_next_month = ?,
comment = ?, card_id = ?, account_id = ?, project_id = ?
WHERE id = ? AND user_id = ?
RETURNING id, purchase, date, amount, amount_paid, remaining, paid, carry_over_next_month, comment, card_id, account_id, project_id, user_id, deleted_at
`

type UpdatePurchaseParams struct {
	Purchase           string         `json:"purchase"`
	Date               string         `json:"date"`
	Amount             int64          `json:"amount"`
	AmountPaid         int64          `json:"amount_paid"`
	CarryOverNextMonth sql.NullInt64  `json:"carry_over_next_month"`
	Comment            sql.NullString `json:"comment"`
	CardID             sql.NullInt64  `json:"card_id"`
	AccountID          sql.NullInt64  `json:"account_id"`
	ProjectID          sql.NullInt64  `json:"project_id"`
	ID                 int64          `json:"id"`
	UserID             sql.NullInt64  `json:"user_id"`
}

func (q *Queries) UpdatePurchase(ctx context.Context, arg UpdatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, updatePurchase,
		arg.Purchase,
		arg.Date,
		arg.Amount,
		arg.AmountPaid,
		arg.CarryOverNextMonth,
		arg.Comment,
		arg.CardID,
		arg.AccountID,
		arg.ProjectID,
		arg.ID,
		arg.UserID,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Purchase,
		&i.Date,
		&i.Amount,
		&i.AmountPaid,
		&i.Remaining,
		&i.Paid,
		&i.CarryOverNextMonth,
		&i.Comment,
		&i.CardID,
		&i.AccountID,
		&i.ProjectID,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}
