// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUserWithPasskey(ctx context.Context, arg CreateUserWithPasskeyParams) (User, error)
	// Initial user registration
	CreateUserWithTelegram(ctx context.Context, arg CreateUserWithTelegramParams) (User, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	// Used to get user profile once registered
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByPassKey(ctx context.Context, passkeyID sql.NullString) (User, error)
	GetUserByTelegramId(ctx context.Context, telegramID sql.NullString) (User, error)
	SoftDeleteUser(ctx context.Context, id int64) error
	UpdateUserPasskey(ctx context.Context, arg UpdateUserPasskeyParams) error
}

var _ Querier = (*Queries)(nil)
