// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUserWithPasskey = `-- name: CreateUserWithPasskey :one
INSERT INTO users (
    name,
    email,
    passkey_id
) VALUES (?, ?, ?) RETURNING id, name, email, telegram_id, passkey_id, registration_date, deleted_at
`

type CreateUserWithPasskeyParams struct {
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	PasskeyID sql.NullString `json:"passkey_id"`
}

func (q *Queries) CreateUserWithPasskey(ctx context.Context, arg CreateUserWithPasskeyParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithPasskey, arg.Name, arg.Email, arg.PasskeyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const createUserWithTelegram = `-- name: CreateUserWithTelegram :one
INSERT INTO users (
    name,
    email,
    telegram_id
) VALUES (?, ?, ?) RETURNING id, name, email, telegram_id, passkey_id, registration_date, deleted_at
`

type CreateUserWithTelegramParams struct {
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	TelegramID sql.NullString `json:"telegram_id"`
}

// Initial user registration
func (q *Queries) CreateUserWithTelegram(ctx context.Context, arg CreateUserWithTelegramParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserWithTelegram, arg.Name, arg.Email, arg.TelegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, telegram_id, passkey_id, registration_date, deleted_at FROM users WHERE email = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, telegram_id, passkey_id, registration_date, deleted_at FROM users WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

// Used to get user profile once registered
func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPassKey = `-- name: GetUserByPassKey :one
SELECT id, name, email, telegram_id, passkey_id, registration_date, deleted_at FROM users WHERE passkey_id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByPassKey(ctx context.Context, passkeyID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPassKey, passkeyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByTelegramId = `-- name: GetUserByTelegramId :one
SELECT id, name, email, telegram_id, passkey_id, registration_date, deleted_at FROM users WHERE telegram_id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByTelegramId(ctx context.Context, telegramID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegramId, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.TelegramID,
		&i.PasskeyID,
		&i.RegistrationDate,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUserPasskey = `-- name: UpdateUserPasskey :exec
UPDATE users SET passkey_id = ? WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserPasskeyParams struct {
	PasskeyID sql.NullString `json:"passkey_id"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateUserPasskey(ctx context.Context, arg UpdateUserPasskeyParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasskey, arg.PasskeyID, arg.ID)
	return err
}
