name: Backend CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Validate code and tests
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Install golangci-lint from source
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

      - name: Execute golangci-lint
        run: golangci-lint run --timeout=5m ./...

      - name: Compiling process
        run: go build -v -o /dev/null ./...

      - name: Execute test suite
        run: go test -v -race -covermode=atomic ./...